# Generated by Django 4.0.4 on 2022-06-23 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('customer_number', models.IntegerField(default=0)),
                ('email', models.EmailField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_number', models.IntegerField(default=0)),
                ('email', models.EmailField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(auto_now=True)),
                ('total', models.FloatField(default=1.0)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS.customers')),
            ],
        ),
    ]
