# Generated by Django 4.0.4 on 2022-06-23 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('unit_price', models.FloatField(default=1.0)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
                ('purchase_price', models.FloatField(default=1.0)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS.products')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_quantity', models.IntegerField(default=1)),
                ('line_total', models.FloatField(default=1.0)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS.invoices')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS.products')),
            ],
        ),
    ]
