# Generated by Django 4.0.5 on 2022-07-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0002_products_purchases_invoice_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
