# Generated by Django 4.0.4 on 2022-07-25 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0004_remove_invoices_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_details',
            name='invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='IMS.invoices'),
        ),
    ]
